# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]
handlers:
- url: /(.*)
  static_files: dist/xlab-app-ng2-mfe/\1
  upload: dist/xlab-app-ng2-mfe/(.*)
- url: /
  static_files: dist/xlab-app-ng2-mfe/index.html
  upload: dist/xlab-app-ng2-mfe/index.html
skip_files:
- ^(?!dist)  # Skip any files not in the dist folder
